services:
  mongo-backup:
    image: mongo
    restart: always
    environment: 
      - DB_APP_URL=mongodb://root:123test@localhost:27017
      - DB_BACKUP_URL=mongodb://root:123backup@localhost:27016
      - CRON_MIN=59
      - CRON_HOUR=23
    