services:
  mongo-backup:
    build: .
    restart: always
    # image: mongo
    environment: 
      - DB_APP_URL=${DB_APP_URL}
      - DB_BACKUP_URL=mongodb://root:backup123@mongo-db:27017
      - CRON_MIN=${CRON_MIN}
      - CRON_HOUR=${CRON_HOUR}
    network_mode: "host"
# use network_mode 'host' apenas se o banco de dados estiver na mesma máquina mas em outro container
# se estiver em outra máquina use o networks: - backup para conectar a mongo-db igual o mongo-express
  mongo-db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=backup123
      - MONGO_INITDB_DATABASE=Backup
    # ports:
    #   - 27019:27017
    networks:
      - backup

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - backup
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://root:backup123@mongo-db:27017

networks:
  backup:
    driver: bridge