services:
  mongo-backup:
    build: .
    restart: always
    # image: mongo
    environment: 
      - DB_APP_URL=${DB_APP_URL}
      - DB_BACKUP_URL=${DB_BACKUP_URL}
      - CRON_MIN=${CRON_MIN}
      - CRON_HOUR=${CRON_HOUR}
    network_mode: "host"
# use network_mode 'host' only if your db service are in other container in the same machine